/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  CardExpensesApi,
  ReceiptMatchApi,
  ReceiptUploadApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BrexExpensesCustom } from "./client-custom";

export class BrexExpenses extends BrexExpensesCustom {
  readonly cardExpenses: CardExpensesApi;
  readonly receiptMatch: ReceiptMatchApi;
  readonly receiptUpload: ReceiptUploadApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.cardExpenses = new CardExpensesApi(configuration);
    this.receiptMatch = new ReceiptMatchApi(configuration);
    this.receiptUpload = new ReceiptUploadApi(configuration);
  }

}
