/* tslint:disable */
/* eslint-disable */
/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateAsyncFileUploadResponse } from '../models';
// @ts-ignore
import { ReceiptMatchRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ReceiptMatchApi - axios parameter creator
 * @export
 */
export const ReceiptMatchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *  The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.  Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they\'re available for your language to upload these files. 
         * @summary Create a new receipt match
         * @param {ReceiptMatchRequest} receiptMatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewReceiptMatch: async (receiptMatchRequest: ReceiptMatchRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'receiptMatchRequest' is not null or undefined
            assertParamExists('createNewReceiptMatch', 'receiptMatchRequest', receiptMatchRequest)
            const localVarPath = `/v1/expenses/card/receipt_match`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: receiptMatchRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/expenses/card/receipt_match',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(receiptMatchRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReceiptMatchApi - functional programming interface
 * @export
 */
export const ReceiptMatchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReceiptMatchApiAxiosParamCreator(configuration)
    return {
        /**
         *  The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.  Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they\'re available for your language to upload these files. 
         * @summary Create a new receipt match
         * @param {ReceiptMatchApiCreateNewReceiptMatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewReceiptMatch(requestParameters: ReceiptMatchApiCreateNewReceiptMatchRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateAsyncFileUploadResponse>> {
            const receiptMatchRequest: ReceiptMatchRequest = {
                receipt_name: requestParameters.receipt_name
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewReceiptMatch(receiptMatchRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ReceiptMatchApi - factory interface
 * @export
 */
export const ReceiptMatchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReceiptMatchApiFp(configuration)
    return {
        /**
         *  The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.  Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they\'re available for your language to upload these files. 
         * @summary Create a new receipt match
         * @param {ReceiptMatchApiCreateNewReceiptMatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewReceiptMatch(requestParameters: ReceiptMatchApiCreateNewReceiptMatchRequest, options?: AxiosRequestConfig): AxiosPromise<CreateAsyncFileUploadResponse> {
            return localVarFp.createNewReceiptMatch(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createNewReceiptMatch operation in ReceiptMatchApi.
 * @export
 * @interface ReceiptMatchApiCreateNewReceiptMatchRequest
 */
export type ReceiptMatchApiCreateNewReceiptMatchRequest = {
    
} & ReceiptMatchRequest

/**
 * ReceiptMatchApiGenerated - object-oriented interface
 * @export
 * @class ReceiptMatchApiGenerated
 * @extends {BaseAPI}
 */
export class ReceiptMatchApiGenerated extends BaseAPI {
    /**
     *  The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.  Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they\'re available for your language to upload these files. 
     * @summary Create a new receipt match
     * @param {ReceiptMatchApiCreateNewReceiptMatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptMatchApiGenerated
     */
    public createNewReceiptMatch(requestParameters: ReceiptMatchApiCreateNewReceiptMatchRequest, options?: AxiosRequestConfig) {
        return ReceiptMatchApiFp(this.configuration).createNewReceiptMatch(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
