/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     * Unique ID for the Budget.
     * @type {string}
     * @memberof Budget
     */
    'id': string;
    /**
     * Name for the Budget.
     * @type {string}
     * @memberof Budget
     */
    'name': string;
}

