/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Department } from './department';

/**
 * 
 * @export
 * @interface ExpandableExpenseDepartment
 */
export interface ExpandableExpenseDepartment {
    /**
     * The unique identifier for the department.
     * @type {string}
     * @memberof ExpandableExpenseDepartment
     */
    'id': string;
    /**
     * The name of the department.
     * @type {string}
     * @memberof ExpandableExpenseDepartment
     */
    'name': string;
}

