/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Payment } from './payment';
import { PaymentInstrument } from './payment-instrument';

/**
 * 
 * @export
 * @interface ExpandableExpensePayment
 */
export interface ExpandableExpensePayment {
    /**
     * Unique ID for the payment.
     * @type {string}
     * @memberof ExpandableExpensePayment
     */
    'id': string;
    /**
     * 
     * @type {PaymentInstrument}
     * @memberof ExpandableExpensePayment
     */
    'payment_instrument': PaymentInstrument;
}

