/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Location } from './location';

/**
 * 
 * @export
 * @interface ExpandableExpenseLocation
 */
export interface ExpandableExpenseLocation {
    /**
     * The unique identifier for the location.
     * @type {string}
     * @memberof ExpandableExpenseLocation
     */
    'id': string;
    /**
     * The name of the location.
     * @type {string}
     * @memberof ExpandableExpenseLocation
     */
    'name': string;
}

