/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Merchant } from './merchant';

/**
 * 
 * @export
 * @interface ExpandableExpenseMerchant
 */
export interface ExpandableExpenseMerchant {
    /**
     * Merchant descriptor
     * @type {string}
     * @memberof ExpandableExpenseMerchant
     */
    'raw_descriptor': string;
    /**
     * https://en.wikipedia.org/wiki/Merchant_category_code
     * @type {string}
     * @memberof ExpandableExpenseMerchant
     */
    'mcc': string;
}

