/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category } from './category';
import { ExpandableExpenseBudget } from './expandable-expense-budget';
import { ExpandableExpenseDepartment } from './expandable-expense-department';
import { ExpandableExpenseLocation } from './expandable-expense-location';
import { ExpandableExpenseMerchant } from './expandable-expense-merchant';
import { ExpandableExpensePayment } from './expandable-expense-payment';
import { ExpandableExpenseUser } from './expandable-expense-user';
import { ExpensePaymentStatus } from './expense-payment-status';
import { ExpenseStatus } from './expense-status';
import { Money } from './money';
import { Receipt } from './receipt';

/**
 * The expense object that has expandable fields, e.g., `location`, `department`, and `receipts`.
 * @export
 * @interface ExpandableExpense
 */
export interface ExpandableExpense {
    /**
     * Unique ID associated with the expense.
     * @type {string}
     * @memberof ExpandableExpense
     */
    'id': string;
    /**
     * The memo of the expense.
     * @type {string}
     * @memberof ExpandableExpense
     */
    'memo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpandableExpense
     */
    'location_id'?: string | null;
    /**
     * 
     * @type {ExpandableExpenseLocation}
     * @memberof ExpandableExpense
     */
    'location'?: ExpandableExpenseLocation;
    /**
     * 
     * @type {string}
     * @memberof ExpandableExpense
     */
    'department_id'?: string | null;
    /**
     * 
     * @type {ExpandableExpenseDepartment}
     * @memberof ExpandableExpense
     */
    'department'?: ExpandableExpenseDepartment;
    /**
     * The last time the expense was updated.
     * @type {string}
     * @memberof ExpandableExpense
     */
    'updated_at': string;
    /**
     * 
     * @type {Category}
     * @memberof ExpandableExpense
     */
    'category'?: Category;
    /**
     * 
     * @type {string}
     * @memberof ExpandableExpense
     */
    'merchant_id'?: string | null;
    /**
     * 
     * @type {ExpandableExpenseMerchant}
     * @memberof ExpandableExpense
     */
    'merchant'?: ExpandableExpenseMerchant;
    /**
     * A list of receipts associated with the expense.
     * @type {Array<Receipt>}
     * @memberof ExpandableExpense
     */
    'receipts'?: Array<Receipt> | null;
    /**
     * 
     * @type {string}
     * @memberof ExpandableExpense
     */
    'budget_id'?: string | null;
    /**
     * 
     * @type {ExpandableExpenseBudget}
     * @memberof ExpandableExpense
     */
    'budget'?: ExpandableExpenseBudget;
    /**
     * 
     * @type {Money}
     * @memberof ExpandableExpense
     */
    'original_amount'?: Money;
    /**
     * The time the purchase was made.
     * @type {string}
     * @memberof ExpandableExpense
     */
    'purchased_at'?: string;
    /**
     * 
     * @type {ExpenseStatus}
     * @memberof ExpandableExpense
     */
    'status'?: ExpenseStatus;
    /**
     * 
     * @type {ExpensePaymentStatus}
     * @memberof ExpandableExpense
     */
    'payment_status'?: ExpensePaymentStatus;
    /**
     * 
     * @type {string}
     * @memberof ExpandableExpense
     */
    'user_id'?: string | null;
    /**
     * 
     * @type {ExpandableExpenseUser}
     * @memberof ExpandableExpense
     */
    'user'?: ExpandableExpenseUser;
    /**
     * 
     * @type {ExpandableExpensePayment}
     * @memberof ExpandableExpense
     */
    'payment'?: ExpandableExpensePayment;
}

