/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type ExpensePaymentStatus = 'NOT_STARTED' | 'PROCESSING' | 'CANCELED' | 'DECLINED' | 'CLEARED' | 'REFUNDING' | 'REFUNDED' | 'CASH_ADVANCE' | 'CREDITED' | 'AWAITING_PAYMENT'

