/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category } from './category';
import { ExpensePaymentStatus } from './expense-payment-status';
import { ExpenseStatus } from './expense-status';
import { Money } from './money';

/**
 * 
 * @export
 * @interface Expense
 */
export interface Expense {
    /**
     * Unique ID associated with the expense.
     * @type {string}
     * @memberof Expense
     */
    'id': string;
    /**
     * The memo of the expense.
     * @type {string}
     * @memberof Expense
     */
    'memo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'location_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'department_id'?: string | null;
    /**
     * The last time the expense was updated.
     * @type {string}
     * @memberof Expense
     */
    'updated_at': string;
    /**
     * 
     * @type {Category}
     * @memberof Expense
     */
    'category'?: Category;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'merchant_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'budget_id'?: string | null;
    /**
     * 
     * @type {Money}
     * @memberof Expense
     */
    'original_amount'?: Money;
    /**
     * The time the purchase was made.
     * @type {string}
     * @memberof Expense
     */
    'purchased_at'?: string;
    /**
     * 
     * @type {ExpenseStatus}
     * @memberof Expense
     */
    'status'?: ExpenseStatus;
    /**
     * 
     * @type {ExpensePaymentStatus}
     * @memberof Expense
     */
    'payment_status'?: ExpensePaymentStatus;
}

