/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type ExpenseStatus = 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'OUT_OF_POLICY' | 'VOID' | 'CANCELED' | 'SPLIT' | 'SETTLED'

