/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The location associated with the expense.
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * The unique identifier for the location.
     * @type {string}
     * @memberof Location
     */
    'id': string;
    /**
     * The name of the location.
     * @type {string}
     * @memberof Location
     */
    'name': string;
}

