/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpandableExpense } from './expandable-expense';

/**
 * 
 * @export
 * @interface PageExpandableExpense
 */
export interface PageExpandableExpense {
    /**
     * 
     * @type {string}
     * @memberof PageExpandableExpense
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<ExpandableExpense>}
     * @memberof PageExpandableExpense
     */
    'items': Array<ExpandableExpense>;
}

