/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The parameter for creating a receipt match.
 * @export
 * @interface ReceiptMatchRequest
 */
export interface ReceiptMatchRequest {
    /**
     * The name of the receipt (with the file extension). It will be used in the matching result email.
     * @type {string}
     * @memberof ReceiptMatchRequest
     */
    'receipt_name': string;
}

