/*
Expenses API


The Expenses API allows you to manage accounting and expenses information.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The parameter for updating an expense.
 * @export
 * @interface UpdateExpenseRequest
 */
export interface UpdateExpenseRequest {
    /**
     * Expense memo.
     * @type {string}
     * @memberof UpdateExpenseRequest
     */
    'memo'?: string | null;
}

